### ISSUE TITLE
Exclude nodes or support virtual nodes on AKS

### ISSUE THREAD

**Issue by claas-fridtjof-lisowski** [cloudability/metrics-agent#111]
We do use a [virtual node](https://docs.microsoft.com/en-us/azure/aks/virtual-nodes) in our AKS cluster.

```
virtual-node-aci-linux            Ready    agent   326d   v1.18.4-vk-azure-aci-v1.3.2
```

It seems that the metrics-agent doesn't know how to handle that one. 
The logs show repeatedly

```
time="2021-02-17T08:58:32Z" level=warning msg="Invalid response 404 URL: https://10.200.10.81:10250/stats/container/ retrying: 1"
time="2021-02-17T08:58:34Z" level=warning msg="Invalid response 404 URL: https://10.200.10.81:10250/stats/container/ retrying: 2"
time="2021-02-17T08:58:34Z" level=warning msg="Warning failed to get node metrics: map[virtual-node-aci-linux:direct connect failed (will attempt proxy): Invalid response 404]"
```

It would be nice to exclude nodes or handle it correctly. - I am not sure yet if this causes dataloss during gathering/uploading of the data as I just installed the 1.4.0-beta version on that cluster.

**Comment by jpepin** [comment]
Thanks for letting us know. It shouldn't prevent the agent from collecting metrics for the rest of the nodes, but we may be unable to provide allocation data for that node. We'll dig into this issue and get some more answers.

In the meantime, you can reduce log noise for this cluster by setting `CLOUDABILITY_COLLECTION_RETRY_LIMIT` to 0 so that the agent doesn't keep retrying a connection to this  node.

**Comment by claas-fridtjof-lisowski** [comment]
After running now for 2 days with the 1.4.0-beta version we don't see any data of that cluster in question in the dashboard.
Besides those warning logs I only can see logs where it says it uploads data:

```
time="2021-02-24T09:06:11Z" level=info msg="Uploading Metrics"
time="2021-02-24T09:06:13Z" level=info msg="Exported metric sample 1234567-87a9-r2d2-8cce-f1860c98090f_20210224090600 to cloudability"
```

our nodes have mixed versions due to the virtual node. First we used the latest version, which works fine for our clusters without the virtual node (we can't control the k8s version of that virtual node) but also that didn't help - no data is shown up in the dashboard.

```
NAME                              STATUS   ROLES   AGE    VERSION
aks-batch-123456-vmss0000tn     Ready    agent   9h     v1.17.13
aks-default-123456-vmss00004h   Ready    agent   5d1h   v1.17.13
aks-large-123456-vmss0000aa     Ready    agent   22d    v1.17.13
virtual-node-aci-linux            Ready    agent   333d   v1.18.4-vk-azure-aci-v1.3.3
```

**Comment by jpepin** [comment]
@claas-fridtjof-lisowski Unfortunately due to the public nature of github, we can't discuss specifics around your account's data handling here. Once you have opened an issue via our official support channels for Apptio Cloudability we will be able to give more details on this specific case and our next steps for resolution.
