### ISSUE TITLE
Unable to pull image via Helm -- Need to Release

### ISSUE THREAD

**Issue by physik932** [cloudability/metrics-agent#83]
Hello!  While utilizing the metrics-agent chart, we were unable to pull the image because the release used in `deployment.yaml` references `image: 'cloudability/metrics-agent:0.1.0`, but this version isn't released on this repository.

https://github.com/cloudability/metrics-agent/blob/master/deploy/charts/metrics-agent/templates/deployment.yaml#L26

If you cut a release for 0.1.0, the image created here should work.  

Thanks for your time!

**Comment by johnjeffers** [comment]
@physik932 The chart's been updated to use `latest` instead of the chart version. This is the same way the Cloudability app works when you generate a template in the app. If you prefer to hardcode the version, you can override it in `values.yaml` https://github.com/cloudability/metrics-agent/pull/84
